[Placeholder] Add dao txs
pokt-network/pocket-js pull request #86
Opened 2023-04-24 20:36 UTC by PoktBlade

2023-04-26 17:37 UTC, PoktBlade commented
To reviewers,

I believe the skeleton of this PR is ready to review with basic validation and test cases for first read. 

Next up is constructing the transaction with the right parameters and ensuring the transaction emitted is accurate to the actual call on my local net, but those changes should be minimal and could be done on a second pass.

2023-05-09 15:24 UTC, rem1niscence requested changes
peer reviewed with @crisog, changes are mostly on typos and gitignore, after these changes are made let's test this on a localnet if you haven't already.

Also please next time separate linting from new features code

2023-05-09 15:24 UTC, rem1niscence commented on .idea/.gitignore
> +# Default ignored files
please remove this file and add the folder to `.gitignore`

2023-05-09 15:24 UTC, rem1niscence commented on .idea/modules.xml
> +<?xml version="1.0" encoding="UTF-8"?>
same here, please remove and add to `.gitignore` the folder

2023-05-09 15:24 UTC, rem1niscence commented on packages/transaction-builder/src/models/proto/tx-signer.proto
> +    bytes FromAddress = 1;
I believe that the `FromAddress` field has a typo, the "f" should be lowercase according to the DAO message params https://github.com/pokt-network/pocket-core/blob/897e267924ab1cd59f545515c1ec329324c31ee8/proto/x/gov/gov.proto

2023-05-09 15:24 UTC, rem1niscence commented on packages/transaction-builder/src/models/proto/tx-signer.proto
> +    bytes ToAddress = 2;
both `FromAddress` and `ToAddress` should be lowercase
```suggestion
    bytes fromAddress = 1;
    bytes toAddress = 2;
```

2023-06-05 06:48 UTC, PoktBlade commented
Successful DAO Transfer (Code 0)

```js
const daoTransfer = tb.govDAOTransfer(
    {
        toAddress: "07a6fca4dea9f01e4c19f301df0d0afac128561b",
        // Amount in uPOKT (1 POKT = 1*10^6 uPOKT)
        action: DAOAction.Transfer,
        amount: "100000",
    }
);
console.log(await tb.submit({txMsg: daoTransfer, fee: "10000"}))
```

Output:
```js
{
  logs: null,
  txHash: 'DA0E9523BD7EA342FFC238C91581C7811E71FA0B4AC3CD4A8BACD8AEDD72766E'
}
```

TX Output:
```js
{
    "hash": "DA0E9523BD7EA342FFC238C91581C7811E71FA0B4AC3CD4A8BACD8AEDD72766E",
    "height": 2,
    "index": 0,
    "proof": {
        "data": null,
        "proof": {
            "aunts": null,
            "index": 0,
            "leaf_hash": null,
            "total": 0
        },
        "root_hash": ""
    },
    "stdTx": {
        "entropy": 7931037553567213,
        "fee": [
            {
                "amount": "10000",
                "denom": "upokt"
            }
        ],
        "memo": "",
        "msg": {
            "type": "gov/msg_dao_transfer",
            "value": {
                "action": "dao_transfer",
                "amount": "100000",
                "from_address": "265e1b97e506019d5de654f2b1b388e52725efbe",
                "to_address": "07a6fca4dea9f01e4c19f301df0d0afac128561b"
            }
        },
        "signature": {
            "pub_key": "dcc7981962d1fe3c2c6689ceefc01f44fdd3b17f00b3a687a0adb944b73cb1cb",
            "signature": "611d9a828c0449f5ca8bfdfdfa77feaf6c1fdb4a04d5f25576df822ecbc2c5444082733d9844ab9f20dc6ea465d0981fb2e68046dd1c3e5c313f6504b290320e"
        }
    },
    "tx": "3AEKWwoVL3guZ292Lk1zZ0RBT1RyYW5zZmVyEkIKFCZeG5flBgGdXeZU8rGziOUnJe++EhQHpvyk3qnwHkwZ8wHfDQr6wShWGxoGMTAwMDAwIgxkYW9fdHJhbnNmZXISDgoFdXBva3QSBTEwMDAwGmQKINzHmBli0f48LGaJzu/AH0T907F/ALOmh6CtuUS3PLHLEkBhHZqCjARJ9cqL/f36d/6vbB/bSgTV8lV234Iuy8LFRECCcz2YRKufINxupGXQmB+y5oBG3Rw+XDE/ZQSykDIOKO3L0qDJp4sO",
    "tx_result": {
        "code": 0,
        "codespace": "",
        "data": null,
        "events": null,
        "info": "",
        "log": "",
        "message_type": "dao_tranfer",
        "recipient": "",
        "signer": "265E1B97E506019D5DE654F2B1B388E52725EFBE"
    }
}
```

2023-06-05 06:53 UTC, PoktBlade commented on packages/transaction-builder/src/models/proto/tx-signer.proto
> +    bytes FromAddress = 1;
If you take a look at the other protos that are self defined, the previous creator also used upper camel case. I do not know if this has a impact on how the protos are autogenerated, and hence why I followed the same pattern.

For example:
https://github.com/pokt-foundation/pocket-js/blob/02f192873c98345134e6fcb8eabf08ca92a22bf7/packages/transaction-builder/src/models/proto/tx-signer.proto#L78

2023-06-05 06:53 UTC, PoktBlade commented on packages/transaction-builder/src/models/proto/tx-signer.proto
> +    bytes ToAddress = 2;
Read other comment in reference to this

2023-06-05 09:27 UTC, PoktBlade commented
All good to review, the only thing that is needed now is a version increment.

2023-06-05 10:57 UTC, PoktBlade commented on packages/transaction-builder/src/models/proto/tx-signer.proto
> +    bytes FromAddress = 1;
ah nevermind, i see what you're saying. Made the protos match - and to answer my own question, the camel case doesn't really matter. Pocket core was just inconsistent in naming them, so I guess we will adopt it here.

2023-06-27 04:58 UTC, PoktBlade commented
@rem1niscence I noticed you updated the versions a couple of days ago - hence what the conflicts are showing. How would you like me to proceed?

2023-07-17 21:53 UTC, rem1niscence approved these changes, later dismissed

2023-07-17 21:53 UTC, rem1niscence commented on packages/transaction-builder/src/models/msgs/msg-proto-gov-change-param.ts
> +      paramVal: Buffer.from(
Is this double `Buffer.from` intentional?

2023-08-29 00:42 UTC, nodiesBlade commented on packages/transaction-builder/src/models/msgs/msg-proto-gov-change-param.ts
> +      paramVal: Buffer.from(
Yes, it's intentional. One to base64 and the other is the tsproto expects a buffer of the base64 encoded string

2023-08-29 00:49 UTC, nodiesBlade commented
Resolved the merge conflict by upgrading the version to 2.2.0

2023-08-29 14:54 UTC, rem1niscence approved these changes

2023-08-29 14:55 UTC, merged